#!/usr/bin/perl

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

my $ALIENARENADIR = "/root/Alien\ Arena";
my $SCREENCMD = "/usr/bin/screen";

# No changes below here...

my $startpath = $ENV{'PATH'};
my $exists = "";

# Set ENV vars
$ENV{'TERM'} = "xterm-256color";

my $running=`ps ax|grep "alienarena-linux64-dedicated"|grep -v grep`;

# check if Alien Arena server process is running
if ($running ne "")
{
	print ("Startupscript already running...\n");
	exit (0);
}

while (-1)
{
	chdir $ALIENARENADIR;
	# check if Alien Arena server process is running
	$running=`ps ax|grep "alienarena-linux64-dedicated"|grep -v grep`;
	if ($running eq "")
	{
		print "Alien Arena server not running\n";
		# See if they want the server started
		if (! -f "$ALIENARENADIR/nostart")
		{
			# The Log Entry
			my $datestring = localtime();
			my $TIME="Alien Arena server Down, Restarting: $datestring";
			open(OUTF, ">>$ALIENARENADIR/AlienArenaScreen.log") || die "Unable to open $ALIENARENADIR/AlienArenaScreen.log for appending";
			print (OUTF "$TIME\n");
			close($OUTF);
			chdir "$ALIENARENADIR";
			print "Starting screen process\n";
			system("$SCREENCMD -fa -S AlienArena -d -U -m ./start-alienarena-linux64-dedicated");
		}
	}
	else
	{
		print "Alien Arena server already running\n";
	}
	# Sleep for 1 minute before checking again
	sleep(60);
}
exit(0);
